"""
Django settings for trove_builder project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno desde el archivo .env en la raíz del
# proyecto (junto a manage.py). Ese archivo NUNCA se sube a git — mira
# .gitignore y .env.example.
load_dotenv(BASE_DIR / ".env")

import sentry_sdk

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""),
    send_default_pii=True,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Si no hay DJANGO_SECRET_KEY en el .env, usa una key de desarrollo (nunca
# la uses así en producción real).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-solo-para-desarrollo-local-no-usar-en-produccion",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Render pone automáticamente el dominio asignado en esta variable — si
# existe, lo agregamos solo para no tener que copiarlo a mano al .env.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

# Necesario desde Django 4+ para aceptar peticiones POST (login, votar,
# comentar, etc.) cuando el sitio corre detrás de HTTPS en un dominio real.
# En local (http://127.0.0.1:8000) no hace falta, por eso queda vacío si no
# se define nada en el .env.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")


# Application definition

INSTALLED_APPS = [
    'builder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trove_builder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trove_builder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# En tu PC (sin DATABASE_URL en el .env) sigue usando el mismo db.sqlite3
# de siempre. En un servidor real (Railway/Render con Postgres), esas
# plataformas definen DATABASE_URL automáticamente y Django la usa sola.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# WhiteNoise sirve los archivos estáticos (CSS, íconos) directamente desde
# Django en producción, sin necesitar un servidor aparte como Nginx —
# perfecto para un despliegue simple en Railway/Render.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    # En tu PC, sigue sirviendo los estáticos como siempre (sin necesitar
    # collectstatic antes de cada runserver).
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # En producción, WhiteNoise sirve los estáticos comprimidos y con hash
    # en el nombre (mejor cache del navegador) directamente desde Django.
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# En desarrollo, si no defines EMAIL_HOST_PASSWORD en el .env, los correos
# (como el de "recuperar contraseña") se imprimen en la terminal en vez de
# enviarse de verdad. En cuanto pones tus credenciales reales en el .env,
# se envían por Gmail SMTP tal como ya lo probaste.

# Railway bloquea las conexiones salientes por SMTP (puertos 25/587/465),
# asi que Gmail SMTP nunca va a poder conectarse desde ahi (se probo y da
# "OSError: Network is unreachable"). La solucion es enviar por la API HTTP
# de Resend en vez de SMTP crudo — HTTPS si esta permitido.
#
# RESEND_API_KEY se crea gratis en https://resend.com (sin tarjeta). Una vez
# verificado el dominio trovebuilder.me ahi, se puede mandar desde
# noreply@trovebuilder.me a cualquier destinatario.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Trove Builder <noreply@trovebuilder.me>")

if RESEND_API_KEY:
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
    ANYMAIL = {
        "RESEND_API_KEY": RESEND_API_KEY,
    }
else:
    # Sin la API key configurada (por ejemplo en desarrollo local), los
    # correos se imprimen en la terminal en vez de fallar o de intentar
    # mandar de verdad.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Sin credenciales configuradas, cae a imprimir el correo en la consola
    # en vez de fallar o enviar con campos vacíos.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Seguridad extra que solo se activa en producción real (DEBUG=False), para
# no complicar el desarrollo local con redirecciones HTTPS que 127.0.0.1
# no tiene.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

