# Generated by Django 6.1.1 on 2026-09-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_gameclass_damage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('weapon', 'Weapon'), ('hat', 'Hat'), ('face', 'Face'), ('ring', 'Ring')], max_length=10)),
                ('tier', models.CharField(blank=True, choices=[('non_crystal', 'No-Crystal (Shadow/Radiant/Stellar)'), ('crystal', 'Crystal')], max_length=15)),
                ('fixed_stats', models.JSONField(blank=True, default=list)),
                ('rollable_stats_by_position', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slot_type', 'tier'],
                'constraints': [models.UniqueConstraint(fields=('slot_type', 'tier'), name='unique_slot_tier')],
            },
        ),
        migrations.CreateModel(
            name='BuildEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_stats', models.JSONField(blank=True, default=list)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='builder.build')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builder.equipmentslot')),
            ],
            options={
                'ordering': ['slot__slot_type'],
            },
        ),
    ]
