# Generated by Django 6.1.1 on 2026-09-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_subclass_level_bonus_progression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('dragon_type', models.CharField(choices=[('normal', 'Dragón normal'), ('primordial', 'Dragón Primordial (de gemas)')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('power_rank_bonus', models.CharField(help_text="Bono de Power Rank que otorga una vez desbloqueado, ej: '+30 PR fijo' o '+10% del PR total de gemas'.", max_length=120)),
            ],
            options={
                'ordering': ['dragon_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='gem',
            name='max_rank',
            field=models.PositiveSmallIntegerField(default=30, help_text='Nivel máximo de la gema. Depende de su rareza real al dropear (Common...Shadow...Radiant...Stellar...Crystal), no del tipo de gema en sí: Stellar tope 25, Crystal tope 30 (confirmado por capturas de pantalla del juego). 30 aquí representa el techo teórico en la mejor rareza posible.'),
        ),
    ]
