# Generated by Django 6.1 on 2026-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_buildfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='power_rank_bonus',
            field=models.CharField(help_text="Bono de Power Rank que otorga una vez desbloqueado, ej: '+30 PR fijo' o '+10% del PR total de gemas'.", max_length=300),
        ),
    ]
