# Generated by Django 6.1.1 on 2026-09-14 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('primary_role', models.CharField(blank=True, choices=[('tank', 'Tank'), ('dps', 'DPS'), ('healer', 'Healer'), ('support', 'Support')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Game classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('gem_type', models.CharField(choices=[('offense', 'Ofensiva'), ('defense', 'Defensiva'), ('utility', 'Utilidad')], max_length=20)),
                ('max_rank', models.PositiveSmallIntegerField(default=9)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('stat_scaling', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('primary_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds_as_primary', to='builder.gameclass')),
                ('secondary_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_as_secondary', to='builder.gameclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='builder.build')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('build', 'user'), name='one_vote_per_user_per_build')],
            },
        ),
        migrations.CreateModel(
            name='BuildGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gem_slots', to='builder.build')),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_builds', to='builder.gem')),
            ],
            options={
                'ordering': ['slot_number'],
                'constraints': [models.UniqueConstraint(fields=('build', 'slot_number'), name='unique_slot_per_build')],
            },
        ),
    ]
