# Generated by Django 6.1.1 on 2026-09-14 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gem',
            name='restricted_to_class',
            field=models.ForeignKey(blank=True, help_text='Si se define, esta gema solo puede usarse con esta clase (Class Gem).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_gems', to='builder.gameclass'),
        ),
        migrations.AlterField(
            model_name='gem',
            name='gem_type',
            field=models.CharField(choices=[('offense', 'Ofensiva'), ('defense', 'Defensiva'), ('utility', 'Utilidad'), ('class', 'Gema de Clase')], max_length=20),
        ),
    ]
