# Generated by Django 6.1.1 on 2026-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_gem_restricted_to_class_alter_gem_gem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclass',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('physical', 'Physical Damage'), ('magic', 'Magic Damage')], help_text='Determina si esta clase escala con Physical Damage o Magic Damage. No restringe qué gemas se pueden equipar, solo cuáles stats sirven.', max_length=10),
        ),
    ]
