# Generated by Django 6.1.1 on 2026-09-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_equipmentslot_buildequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gem',
            name='damage_variant',
            field=models.CharField(blank=True, choices=[('fierce', 'Fierce (solo Physical Damage)'), ('arcane', 'Arcane (solo Magic Damage)'), ('universal', 'Universal (Empowered/Class, cualquier tipo de daño)')], help_text='Solo aplica a gemas menores (Shadow/Radiant/Stellar): son Fierce (Physical) o Arcane (Magic), nunca ambas. Empowered/Class gems son universales.', max_length=10),
        ),
        migrations.AddField(
            model_name='gem',
            name='element',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('air', 'Air'), ('fire', 'Fire'), ('cosmic', 'Cosmic')], max_length=10),
        ),
    ]
