# Generated by Django 6.1.1 on 2026-09-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_gem_damage_variant_gem_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('passive_description', models.TextField(help_text='Descripción de la habilidad pasiva que se activa en combate.')),
                ('bonus_stat', models.CharField(help_text="Stat que otorga como bono fijo al equipar esta subclase, ej: 'Critical Damage', 'Jump', 'Magic Find'.", max_length=60)),
                ('bonus_range', models.CharField(blank=True, help_text="Rango del bono segun el nivel de subclase (1 a 30), ej: '+1% a +20%'.", max_length=40)),
                ('game_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='builder.gameclass')),
            ],
            options={
                'ordering': ['game_class__name'],
            },
        ),
        migrations.AddField(
            model_name='build',
            name='subclass',
            field=models.ForeignKey(blank=True, help_text='Subclase equipada (la habilidad pasiva de OTRA clase). Nunca puede ser la subclase de la propia primary_class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_builds', to='builder.subclass'),
        ),
    ]
