# Generated by Django 6.1.1 on 2026-09-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_subclass_build_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclass',
            name='level_bonus_progression',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subclass',
            name='tier_progression',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='passive_description',
            field=models.TextField(help_text='Descripción corta de la pasiva (efecto del Tier I, como referencia rápida).'),
        ),
    ]
