# Generated by Django 6.1.1 on 2026-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_dragon_alter_gem_max_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildgem',
            name='chosen_stats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
