# Generated by Django 6.1.1 on 2026-09-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_buildgem_chosen_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingHiddenEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('game_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ring_hidden_effect', to='builder.gameclass')),
            ],
            options={
                'ordering': ['game_class__name'],
            },
        ),
    ]
