# Generated by Django 6.1.1 on 2026-09-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_buildcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ringhiddeneffect',
            options={'ordering': ['game_class__name', 'availability']},
        ),
        migrations.AddField(
            model_name='ringhiddeneffect',
            name='availability',
            field=models.CharField(choices=[('signatory_or_mystic', 'Signatory o Mystic Ring'), ('mystic_only', 'Solo en Mystic Ring'), ('shared_dodge', 'Efecto compartido de esquive (Mystic Ring)')], default='mystic_only', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ringhiddeneffect',
            name='game_class',
            field=models.ForeignKey(blank=True, help_text="En blanco solo para el 'Rushed Escape' generico, compartido por todas las clases excepto Shadow Hunter.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ring_hidden_effects', to='builder.gameclass'),
        ),
    ]
