# Generated by Django 6.1.1 on 2026-09-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_alter_ringhiddeneffect_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentslot',
            name='tier',
            field=models.CharField(blank=True, choices=[('non_crystal', 'No-Crystal (Shadow/Radiant/Stellar)'), ('crystal', 'Crystal'), ('signatory', 'Signatory'), ('wisdom', 'Wisdom'), ('power', 'Power'), ('vitality', 'Vitality'), ('delving', 'Delving')], max_length=15),
        ),
    ]
