# Generated by Django 6.1 on 2026-09-17 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Reportar un problema'), ('idea', 'Sugerir una idea'), ('other', 'Otro')], default='idea', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('reviewed', 'Revisada'), ('done', 'Hecha')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
