# Generated by Django 6.1.1 on 2026-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ally', 'Ally'), ('emblem', 'Emblem'), ('flask', 'Flask')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170)),
                ('source_path', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text="Subcategoria tal como la reporta el codex (ej: 'minion', 'buff').", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('tradable', models.BooleanField(default=False)),
                ('mastery', models.PositiveIntegerField(blank=True, null=True)),
                ('power_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('abilities', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'source_path'), name='unique_equipmentitem_kind_source_path')],
            },
        ),
    ]
