# Generated by Django 6.1.1 on 2026-09-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_alter_equipmentitem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='ally',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'ally'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_as_ally', to='builder.equipmentitem'),
        ),
        migrations.AddField(
            model_name='build',
            name='banner',
            field=models.ForeignKey(blank=True, help_text='Algunos banners dan Physical Damage o Magic Damage: conviene elegir el que combine con el damage_type de la clase.', limit_choices_to={'kind': 'banner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_as_banner', to='builder.equipmentitem'),
        ),
        migrations.AddField(
            model_name='build',
            name='emblem',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'emblem'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_as_emblem', to='builder.equipmentitem'),
        ),
        migrations.AddField(
            model_name='build',
            name='flask',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'flask'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds_as_flask', to='builder.equipmentitem'),
        ),
    ]
