# Generated by Django 6.1.1 on 2026-09-23 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0020_build_ally_build_banner_build_emblem_build_flask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="language",
            field=models.CharField(
                choices=[("es", "Español"), ("en", "English")],
                default="es",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="remixed_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Build original de la que se hizo este remix (se conserva el credito).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remixes",
                to="builder.build",
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="status",
            field=models.CharField(
                choices=[
                    ("current", "Al día"),
                    ("review", "Revisar"),
                    ("stale", "Obsoleto"),
                ],
                default="current",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Ultima vez que el autor guardo o confirmo que la build sigue al dia.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GameVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("released_on", models.DateField()),
                ("patch_notes_url", models.URLField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "affected_classes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clases que este parche cambio. Sus builds se marcaran para revisar.",
                        related_name="affected_by_versions",
                        to="builder.gameclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-released_on"],
            },
        ),
        migrations.AddField(
            model_name="build",
            name="game_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Version del juego en la que se creo o confirmo por ultima vez.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="builds",
                to="builder.gameversion",
            ),
        ),
        migrations.CreateModel(
            name="BuildRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="builder.build",
                    ),
                ),
                (
                    "game_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="builder.gameversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("build", "number"),
                        name="unique_revision_number_per_build",
                    )
                ],
            },
        ),
    ]
