# Generated by Django 6.1.1 on 2026-09-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0022_seed_rematch_and_initial_revisions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("comment", "comentó en tu build"),
                    ("vote", "votó tu build"),
                    ("review", "El nuevo parche puede afectar tu build"),
                ],
                max_length=10,
            ),
        ),
    ]
